[project]
name = "graphvisualizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PENTELA RAGHU RAM", email = "raghuram@example.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pygame-ce>=2.5.8",
]

[project.scripts]
graphvisualizer = "graphvisualizer:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"

[tool.uv.extra-build-dependencies]
pygame = ["setuptools"]
